### ISSUE TITLE
[Bug] broken links reported on #find-the-right-solution-for-your-business

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/BCWebMaps-Options#27]
A Service Desk inquiry was forwarded to my team:
 
 _I noticed a couple of broken links (in red outline) on the following page, which I think you manage?_ 
 
_https://bcgov.github.io/bcwebmaps-options/#find-the-right-solution-for-your-business_

![image](https://user-images.githubusercontent.com/26335003/106533775-95c58d00-64a7-11eb-9047-2eabec91e311.png)

Specifically: Leaflet, Mapbox GL JS are broken.  That content no longer seems included as it once was; probably an oversight in removing it.

**Comment by webgismd** [comment]
fixed see https://github.com/bcgov/bcwebmaps-options/commit/0b80d22c3c5fa803582d10ae87d0ec0103355922
