### ISSUE TITLE
Can you move the Look and Feel section to the top of page?

### ISSUE THREAD

**Issue by webgismd** [bcgov/BCWebMaps-Options#7]
@roboost

**Comment by roboost** [comment]
As a web map designer, I want to interact with examples early on to help me understand the functionality of each framework. That's just my tendency however, whereas other users may prefer to read first and test second.

**Comment by webgismd** [comment]
this is complete.. - https://github.com/bcgov/BCWebMaps-Options/commit/94f785563d2f50ac975b791a46586328808bf25a
